from typing import Any, Dict, List, Optional
from typing_extensions import TypedDict


class InterviewState(TypedDict):
    """
    Shared state passed between every node in the LangGraph interview agent.

    Fields are populated incrementally as the graph executes:
      - ``fetch_session``      fills session_data, conversation_history, current_question_no
      - ``generate_question``  fills current_question, current_taxonomy_level
      - ``evaluate_answer``    fills evaluation_score, evaluation_feedback
      - ``generate_report``    fills final_report and sets is_interview_complete = True

    ``mode`` controls the routing decision after fetch_session:
      - ``"start"``  → skip evaluation, go straight to question generation
      - ``"answer"`` → evaluate the provided answer first, then decide next step
    """

    # ── Inputs ──────────────────────────────────────────────────────────────
    session_id: str
    mode: str                         # "start" | "answer"
    answer_text: Optional[str]        # Populated only in "answer" mode

    # ── Loaded from DB by fetch_session ─────────────────────────────────────
    session_data: Optional[Dict[str, Any]]
    conversation_history: Optional[List[Dict[str, Any]]]
    current_question_no: int          # Next question to be generated (1-based)

    # ── Generated by generate_question ──────────────────────────────────────
    current_question: Optional[str]
    current_taxonomy_level: Optional[str]

    # ── Generated by evaluate_answer ────────────────────────────────────────
    evaluation_score: Optional[float]
    evaluation_feedback: Optional[str]

    # ── Generated by generate_report ────────────────────────────────────────
    final_report: Optional[Dict[str, Any]]

    # ── Control flow ────────────────────────────────────────────────────────
    is_interview_complete: bool
    error: Optional[str]
